local ControlSpec = require 'controlspec'
local Formatters = require 'jah/formatters'
local Haven = {}


local specs = {}

-- Autogenerated using Engine_Haven.generateLuaEngineModuleSpecsSection

specs.freq1 = ControlSpec.new(10, 200, "exp", 0.0, 20, "Hz")
specs.freq2 = ControlSpec.new(1000, 12000, "exp", 0.0, 4000, "Hz")
specs.amp1 = ControlSpec.new(0, 1, "linear", 0.0, 0, "")
specs.amp2 = ControlSpec.new(0, 1, "linear", 0.0, 0, "")
specs.inAmp = ControlSpec.new(0, 1, "linear", 0.0, 0, "")
specs.fdbck = ControlSpec.new(-1, 1, "linear", 0.0, 0.03, "")

Haven.specs = specs

local function bind(paramname, id, formatter)
  params:add_control(paramname, specs[id], formatter)
  params:set_action(paramname, engine[id])
end

function Haven.add_params()
  bind("freq1", "freq1")
  bind("amp1", "amp1")
  bind("freq2", "freq2")
  bind("amp2", "amp2")
  bind("inAmp", "inAmp")
  bind("fdbck", "fdbck")
end

return Haven


